apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-app.yaml
  - namespace-observability.yaml
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres.yaml
  - app-configmap.yaml
  - app-secret.yaml
  - app-deployment.yaml
  - otel-secret.yaml
  - otel-collector-configmap.yaml
  - otel-collector.yaml
