apiVersion: v1
kind: Secret
metadata:
  name: azure-monitor-secret
  namespace: observability
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=e6d3b337-f423-4e28-bd3c-7a29531a0a1c;IngestionEndpoint=https://germanywestcentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://germanywestcentral.livediagnostics.monitor.azure.com/;ApplicationId=cd4f8ca5-37d3-4b36-94eb-b0da5d5b1666
